<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="../../../../">KumbiaPHP</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="../../../../">Home</a></li>
              <li><?php echo Html::link('pages/show/kumbia/status/', 'Config', 'title="Ver configuración de la aplicación"') ?></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tutoriales <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a target="_blank" href="http://soyprogramador.liz.mx/probando-sqlite-en-kumbiaphp/">Probando SQLite en KumbiaPHP</a></li>
                  <li><a target="_blank" href="http://soyprogramador.liz.mx/configuracin-de-kumbiaphp-en-produccin/">Configuraci&oacute;n para producci&oacute;n</a></li>
                  <li><a target="_blank" href="http://soyprogramador.liz.mx/controlando-el-tipo-de-vista-a-mostrar-para-una-accin-dada/">Opciones para VIEW</a></li>
                  <li><a target="_blank" href="http://soyprogramador.liz.mx/agregar-titulo-de-pagina-con-kumbiaphp/">Establecer titulo de p&aacute;gina</a></li>
                  <li><a target="_blank" href="http://soyprogramador.liz.mx/corriendo-kumbiaphp-en-un-subdominio/">Configuraci&oacute;n para subdominio</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Archivos</li>
                  <li><a target="_blank" href="http://soyprogramador.liz.mx/subiendo-archivos-con-kumbiaphp-parte-1-3/">Subiendo archivos Parte 1-3</a></li>
                </ul>
              </li>
            </ul>
            <form class="navbar-form pull-right">
              <input class="span2" type="text" placeholder="Email">
              <input class="span2" type="password" placeholder="Password">
              <button type="submit" class="btn">Sign in</button>
            </form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>