	<div class="row">
		<div class="page-header span7">
			<h1>KumbiaPHP está listo para usarse</h1>
		</div>
		<div id='logo-kumbia' class="span4"><?php echo Html::img('default/kumbia.png','KumbiaPHP logo') ?></div>
	</div>
		
    <div id='info' class="well">
        <p><strong>Bienvenido a KumbiaPHP Framework</strong>. El framework ya está listo para desarrollar aplicaciones web con PHP, rápida y fácilmente
       , sin tener que reinventar la rueda, y preocupandose por lo más importante, la lógica de su aplicación.</p>
        
       
		
    </div>
	 <h2>Como empezar</h2>
        <p>En nuestra <a href="http://wiki.kumbiaphp.com/">wiki</a> podrás encontrar información actualizada sobre el uso del framework,
        si estas comenzando con <em>KumbiaPHP</em> deberías realizar  la
	 <strong><a href="http://wiki.kumbiaphp.com/Hola_Mundo_KumbiaPHP_Framework">Aplicación Hola Mundo</a></strong>
        tambien puede interesarte saber sobre:</p>
		
		
	<div class="row">
        <div class="span4">
		<h2>Recursos</h2>
          	<blockquote>
		<a href="http://wiki.kumbiaphp.com/Beta2_CRUD_en_KumbiaPHP_Framework">Creacion de CRUD(Create, Read, Update, Delete)</a>
		</blockquote>
		<blockquote>
			<a href="http://wiki.kumbiaphp.com/Como_Usar_los_Modelos_en_KumbiaPHP">Uso de modelos</a>
		</blockquote>
		<blockquote>
			<a href="http://soyprogramador.liz.mx/entendiendo-el-nombrado-de-modelos-kumbiaphp/">Entendiendo el nombrado de modelos</a>
		</blockquote>
		<blockquote>
		<a href="http://wiki.kumbiaphp.com/KumbiaPHP_Framework_Versi%C3%B3n_1.0_Spirit#databases.ini">Configurar conexiones a bases de datos</a>
		</blockquote>
        </div>
        <div class="span4">
          <h2><a href="http://kumbiaphp.info" target="_blank">Kumbiaphp.info</a></h2>
          <p>En esta web podras encontrar mas información sobre el uso del framework y las novedades que sucedan (Sitio no oficial, pero si interesante)</p>
          <p><a class="btn btn-info" href="http://kumbiaphp.info" target="_blank">View details »</a></p>
       </div>
        <div class="span4">
          <h2><a href="http://soyprogramador.liz.mx" target="_blank">soyprogramador.liz.mx</a></h2>
          <p>Es un blog donde encontraras informaci&oacute;n interesante relacionada con el desarrollo web.</p>
          <p><a class="btn" href="http://soyprogramador.liz.mx" target="_blank">View details »</a></p>
        </div>
     </div>
		
		
		

	
		<p>Estos son solo algunos ejemplos puedes ver más en la <a href="http://wiki.kumbiaphp.com/Categor%C3%ADa:Tutoriales_KumbiaPHP" title="Tutoriales KumbiaPHP">sección de tutoriales de la wiki</a></p>