<footer>
	<div class="container">
		<div class="row">
			<div class='span4'><a href='http://wiki.kumbiaphp.com/Team_Development_KumbiaPHP_Framework'  target="_blank">© 2007 - <?php echo date('Y');?> KumbiaPHP Team</a></div>
			<div class=' span4'><a href="http://kumbiaphp.info/" target="_blank">App by kumbiaphp.info</a></div>
			<div class=' span4'><p><?php echo 'Tiempo: '.round((microtime(1)-START_TIME),4).' seg.'; echo ', Memoria Usada: '.number_format(memory_get_usage() / 1048576, 2).' MB';?></p></div>
		</div>
	</div>
</footer>

