<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>KumbiaPHP con Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="kumbiaphp.info">
	
 <?php Tag::css('bootstrap/bootstrap.min') ?>
  <?php Tag::css('bootstrap/bootstrap-responsive.min') ?>
  <?php Tag::css('style') ?>
  <?php Tag::css('flash') ?>
  <?php echo Html::includeCss() ?>

    <!-- Le styles -->
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
   <link rel="shortcut icon" href="http://foro.kumbiaphp.com/themes/kumbia/design/favicon.png" type="image/x-icon" />
  </head>

  <body> 
	 <?php View::partial('navbar') ?>

    <div class="container">
		<?php View::content(); ?>
    </div> <!-- /container -->
	
	 <?php View::partial('kumbia/footer') ?>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <?php echo Tag::js("jquery/jquery.min"); ?>
    <?php echo Tag::js("jquery/jquery.kumbiaphp.min"); ?>
    <?php echo Tag::js("bootstrap/bootstrap.min"); ?>

  </body>
</html>
